### ISSUE TITLE
Diskussion der Ergebnisse

### ISSUE THREAD

**Issue by TimSchmale** [NeMaHo/Gruppenarbeit#7]
Aufgabenteil 5: Vergleich der herausgearbeiteten Ergebnisse mit den Inputs bei der Datensatzerstellung.

**Comment by smaier1509** [comment]
Ja gut, das mit den Dezimalzahlen ist auch wohl wahr. Und das Interesse an Programmieren hätte bei Data Science auch höher eingestuft werden sollen. Ich denke damit haben wir auch alles wichtige zusammengefasst und können auch das Issue und die Diskussion schließen ?
